#!/bin/sh

folder=$HOME/notes/

menu_dir() {
    fzf --style full \
        --no-border \
        --prompt "> " \
        --layout reverse \
        --input-label ' 󰍉 Search ' \
        --bind 'result:transform-list-label:printf " %s directories " "$FZF_MATCH_COUNT"' \
        --no-preview \
        --color 'list-border:#669966,list-label:#99cc99' \
        --color 'input-border:#996666,input-label:#ffcccc'    
}

menu_name() {
    fzf --style full \
        --no-border \
        --prompt "> " \
        --input-label ' 󰍉 Enter a name ' \
        --no-preview \
        --print-query \
        --color 'input-border:#996666,input-label:#ffcccc' \
        < /dev/null
}

menu_with_preview() {
    fzf --style full \
        --no-border \
        --prompt "> " \
        --layout reverse \
        --bind 'result:transform-list-label:
        [ -z "$FZF_QUERY" ] && \
            printf " %s notes " "$FZF_MATCH_COUNT" || \
            printf " %s matches for [%s] " "$FZF_MATCH_COUNT" "$FZF_QUERY"
        ' \
        --input-label ' 󰍉 Search ' \
        --no-preview \
        --color 'list-border:#669966,list-label:#99cc99' \
        --color 'input-border:#996666,input-label:#ffcccc'
}

format_list() {
    while IFS= read -r line; do
        case "$line" in
            "New") printf '%s\n' "󰐕 New (create a new note)" ;;
            *.md) printf '󰍔 %s\n' "$line" ;;
        esac
    done
}

format_dirs() {
    while IFS= read -r line; do
        printf '%s\n' "$line"
    done
}

newnote() {
    dir="$(find "$folder" -type d | format_dirs | menu_dir)" || exit 0
    dir="${dir#  }"
    : "${dir:=$folder}"
    fzf_output=$(menu_name)
    fzf_status=$? 
    [ $fzf_status -eq 130 ] && exit 0
    name=$(printf '%s\n' "$fzf_output" | head -n 1)
    : "${name:=$(date +%F_%H-%M-%S)}"
    setsid -f "$TERMINAL" -e "$EDITOR" "${dir%/}/$name.md" >/dev/null 2>&1
}

selected() {
    choice=$(
    printf "New\n$(find "$folder" -type f -name "*.md" 2>/dev/null)" | sed 's|/.*notes/||'\
        | format_list \
        | menu_with_preview
    )
    choice=$(printf '%s\n' "$choice" | sed 's/^[^ ]* *//') 
    [ -z "$choice" ] && exit 0
    case $choice in
        "New (create a new note)") newnote ;;
        *.md) setsid -f "$TERMINAL" -e "$EDITOR" "$folder$choice" >/dev/null 2>&1 ;;
        *)    exit 0 ;;
    esac
}

selected
